# Generated by Django 1.10 on 2017-07-05 13:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoeboard',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=9),
        ),
    ]
